// src/lib/sections/Team.svelte
<script>
	import { TEAM, PEOPLE } from '$src/constants'
	import Figure from '$lib/common/Figure.svelte'
	import Markdown from '$lib/common/Markdown.svelte'
</script>

<section id="team">
	<div class="inner">
		<!-- <div class="overline">
			{TEAM.overline}
		</div> -->
		<h2>
			{TEAM.title}
		</h2>

		<p>
			
		</p>

		<ul class="cols">
			{#each PEOPLE as person}
				<li class="col">
					<Figure
						src="/images/photos/syw_{person.slug}.jpg"
						alt="Portrait of {person.name}"
						caption="Photo by Roshni Khatri"
					/>
					<div class="label">
						<div class="name">
							{person.name}
						</div>
						<div class="website">
							<a
								href="{person.website}"
								target="_blank"
								class="button"
							>
								{person.website.replace('https://', '')}
								<!-- Website -->
							</a>
						</div>
					</div>
					<div class="role">
						{person.role}
					</div>
					<div class="bio">
						<Markdown
							content={person.bio}
						/>
					</div>
				</li>
			{/each}
		</ul>
	</div>
</section>

<style>
	ul {
		list-style: none;
		padding-left: 0;
		margin: 0 calc(var(--space-2) * -1);
		max-width: unset;
	}
	li {
/*		max-width: 400px;*/
		padding: 0 var(--space-2) var(--space-10) var(--space-2);
		line-height: 1.3;
	}
	img {
		width: 100%;
	}
	.label {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		justify-content: space-between;
	}
	.name {
		font-weight: var(--font-weight-body-bold);
		width: 160px;
	}
	.role {
		font-size: var(--text-2);
		white-space: nowrap;
		opacity: 0.5;
	}
	.website {
		font-size: var(--text-1);
	}
	.bio {
		margin-top: var(--space-2);
		font-size: var(--text-2);
	}
</style>

// src/components/home/Team/Team.tsx
import { getLang } from "@/utils/selectors";
import { TEAM_ITEMS } from "./utils/constants";
import Markdown from "@/components/common/Markdown/Markdown";

export default function Team() {
	return (
		<>
			<div
				className="HomeSectionInner"
			>
				<hgroup>
					<h2
						className="HomeSectionTitle"
					>
						{getLang("home", "team", "title")}
					</h2>
				</hgroup>
				<ul
					className="TeamItems"
				>
					{TEAM_ITEMS.map((item: any, index: number) =>
						<li
							key={index}
							className="TeamItem"
						>
							<img
								src={`/images/team/${item.slug}.jpg`}
								alt={`Portrait of ${item.name}`}
								// caption="Photo by Roshni Khatri"
							/>
							<hgroup
								className="TeamItemHeading"
							>
								<h3
									className="TeamItemName"
								>
									{item.name}
								</h3>
								<div
									className="TeamItemWebsite"
								>
									<a
										href={item.website}
										target="_blank"
										rel="noreferrer nofollow"
									>
										{item.website.replace("https://", "")}
									</a>
								</div>
							</hgroup>
							<div
								className="TeamItemRole"
							>
								{item.role}
							</div>
							<div
								className="TeamItemBio"
							>
								<Markdown>
									{item.bio}
								</Markdown>
							</div>
						</li>
					)}
				</ul>
			</div>
		</>
	);
}
